export const doctorSpecializations = [
  { value: "general_practitioner", label: "General Practitioner" },
  { value: "cardiologist", label: "Cardiologist" },
  { value: "dermatologist", label: "Dermatologist" },
  { value: "pediatrician", label: "Pediatrician" },
  { value: "gynecologist", label: "Gynecologist" },
  { value: "orthopedic", label: "Orthopedic Surgeon" },
  { value: "neurologist", label: "Neurologist" },
  { value: "psychiatrist", label: "Psychiatrist" },
  { value: "ophthalmologist", label: "Ophthalmologist" },
  { value: "ent", label: "ENT Specialist" },
  { value: "dentist", label: "Dentist" },
  { value: "urologist", label: "Urologist" },
  { value: "gastroenterologist", label: "Gastroenterologist" },
  { value: "pulmonologist", label: "Pulmonologist" },
  { value: "endocrinologist", label: "Endocrinologist" },
  { value: "oncologist", label: "Oncologist" },
  { value: "radiologist", label: "Radiologist" },
  { value: "anesthesiologist", label: "Anesthesiologist" },
  { value: "pathologist", label: "Pathologist" },
  { value: "physiotherapist", label: "Physiotherapist" },
  { value: "nephrologist", label: "Nephrologist" },
  { value: "rheumatologist", label: "Rheumatologist" },
  { value: "allergist", label: "Allergist" },
  { value: "emergency_medicine", label: "Emergency Medicine" },
  { value: "other", label: "Other" },
]